export const OrderLoading=()=>{
    return<>
    <svg
    xmlns="http://www.w3.org/2000/svg"
    className="w-full h-full sm:hidden mt-4"
    fill="none"
    viewBox="0 0 605 462"
  >
    <path fill="#1E1E1E" d="M0 0H605V462H0z"></path>
    <path
      fill="#fff"
      d="M0 0H1018V868H0z"
      transform="translate(-181 -93)"
    ></path>
    <rect width="605" height="462" fill="#F8F8F8" rx="9"></rect>
    <rect
      width="213"
      height="53"
      x="12"
      y="8"
      fill="#BBBEC5"
      fillOpacity="0.7"
      rx="10"
    ></rect>
    <rect
      width="213"
      height="53"
      x="12"
      y="86"
      fill="#BBBEC5"
      fillOpacity="0.7"
      rx="10"
    ></rect>
    <rect
      width="213"
      height="53"
      x="12"
      y="164"
      fill="#BBBEC5"
      fillOpacity="0.7"
      rx="10"
    ></rect>
    <rect
      width="213"
      height="53"
      x="12"
      y="242"
      fill="#BBBEC5"
      fillOpacity="0.7"
      rx="10"
    ></rect>
    <rect
      width="213"
      height="53"
      x="12"
      y="320"
      fill="#BBBEC5"
      fillOpacity="0.7"
      rx="10"
    ></rect>
    <rect
      width="213"
      height="53"
      x="12"
      y="398"
      fill="#BBBEC5"
      fillOpacity="0.7"
      rx="10"
    ></rect>
    <rect
      width="314"
      height="53"
      x="281"
      y="8"
      fill="#BBBEC5"
      fillOpacity="0.7"
      rx="10"
    ></rect>
    <rect
      width="314"
      height="53"
      x="281"
      y="86"
      fill="#BBBEC5"
      fillOpacity="0.7"
      rx="10"
    ></rect>
    <rect
      width="314"
      height="53"
      x="281"
      y="164"
      fill="#BBBEC5"
      fillOpacity="0.7"
      rx="10"
    ></rect>
    <rect
      width="314"
      height="53"
      x="281"
      y="242"
      fill="#BBBEC5"
      fillOpacity="0.7"
      rx="10"
    ></rect>
    <rect
      width="314"
      height="53"
      x="281"
      y="320"
      fill="#BBBEC5"
      fillOpacity="0.7"
      rx="10"
    ></rect>
    <rect
      width="314"
      height="53"
      x="281"
      y="398"
      fill="#BBBEC5"
      fillOpacity="0.7"
      rx="10"
    ></rect>
  </svg>
    <svg
    xmlns="http://www.w3.org/2000/svg"
    className="w-full h-full sm:hidden mt-4"
    fill="none"
    viewBox="0 0 605 462"
  >
    <path fill="#1E1E1E" d="M0 0H605V462H0z"></path>
    <path
      fill="#fff"
      d="M0 0H1018V868H0z"
      transform="translate(-181 -93)"
    ></path>
    <rect width="605" height="462" fill="#F8F8F8" rx="9"></rect>
    <rect
      width="213"
      height="53"
      x="12"
      y="8"
      fill="#BBBEC5"
      fillOpacity="0.7"
      rx="10"
    ></rect>
    <rect
      width="213"
      height="53"
      x="12"
      y="86"
      fill="#BBBEC5"
      fillOpacity="0.7"
      rx="10"
    ></rect>
    <rect
      width="213"
      height="53"
      x="12"
      y="164"
      fill="#BBBEC5"
      fillOpacity="0.7"
      rx="10"
    ></rect>
    <rect
      width="213"
      height="53"
      x="12"
      y="242"
      fill="#BBBEC5"
      fillOpacity="0.7"
      rx="10"
    ></rect>
    <rect
      width="213"
      height="53"
      x="12"
      y="320"
      fill="#BBBEC5"
      fillOpacity="0.7"
      rx="10"
    ></rect>
    <rect
      width="213"
      height="53"
      x="12"
      y="398"
      fill="#BBBEC5"
      fillOpacity="0.7"
      rx="10"
    ></rect>
    <rect
      width="314"
      height="53"
      x="281"
      y="8"
      fill="#BBBEC5"
      fillOpacity="0.7"
      rx="10"
    ></rect>
    <rect
      width="314"
      height="53"
      x="281"
      y="86"
      fill="#BBBEC5"
      fillOpacity="0.7"
      rx="10"
    ></rect>
    <rect
      width="314"
      height="53"
      x="281"
      y="164"
      fill="#BBBEC5"
      fillOpacity="0.7"
      rx="10"
    ></rect>
    <rect
      width="314"
      height="53"
      x="281"
      y="242"
      fill="#BBBEC5"
      fillOpacity="0.7"
      rx="10"
    ></rect>
    <rect
      width="314"
      height="53"
      x="281"
      y="320"
      fill="#BBBEC5"
      fillOpacity="0.7"
      rx="10"
    ></rect>
    <rect
      width="314"
      height="53"
      x="281"
      y="398"
      fill="#BBBEC5"
      fillOpacity="0.7"
      rx="10"
    ></rect>
  </svg>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    className="h-full w-full mt-8 hidden sm:block"
    fill="none"
    viewBox="0 0 1432 754"
  >
    <path fill="#1E1E1E" d="M0 0H1432V754H0z"></path>
    <g clipPath="url(#clip0_0_1)">
      <path
        fill="#fff"
        d="M0 0H1444V868H0z"
        transform="translate(-12 -114)"
      ></path>
      <g>
        <rect  width="1444" height="907" fill="#F8F8F8" rx="9"></rect>
        <rect
        className="animate-pulse"
          width="1415"
          height="110"
          x="15"
          y="13"
          fill="#BBBEC5"
          fillOpacity="0.7"
          rx="10"
        ></rect>
        <g>
          <rect
            width="1408"
            height="108"
            x="22"
            y="170"
            fill="#EBEAEA"
            rx="8"
          ></rect>
          <g>
            <rect
            
              width="195"
              height="65"
              className="animate-pulse"
              x="42"
              y="194"
              fill="#CDD0D4"
              rx="8"
            ></rect>
            <rect
              width="195"
              height="65"
              x="275"
              y="194"
              fill="#CDD0D4"
              rx="8"
            ></rect>
            <rect
            className="animate-pulse"
              width="195"
              height="65"
              x="508"
              y="194"
              fill="#CDD0D4"
              rx="8"
            ></rect>
            <rect
              width="195"
              height="65"
              x="741"
              y="194"
              fill="#CDD0D4"
              rx="8"
            ></rect>
            <rect
              width="195"
              height="65"
              x="974"
              y="194"
              fill="#CDD0D4"
              rx="8"
            ></rect>
            <rect
              width="195"
              height="65"
              x="1207"
              y="194"
              fill="#CDD0D4"
              rx="8"
            ></rect>
          </g>
        </g>
        <g>
          <rect
          className="animate-pulse"
            width="1408"
            height="108"
            x="22"
            y="413"
            fill="#EBEAEA"
            rx="8"
          ></rect>
          <g>
            <rect
            className="animate-pulse"
              width="195"
              height="65"
              x="42"
              y="437"
              fill="#CDD0D4"
              rx="8"
            ></rect>
            <rect
              width="195"
              height="65"
              x="275"
              y="437"
              fill="#CDD0D4"
              rx="8"
            ></rect>
            <rect
              width="195"
              height="65"
              x="508"
              y="437"
              fill="#CDD0D4"
              rx="8"
            ></rect>
            <rect
            className="animate-pulse"
              width="195"
              height="65"
              x="741"
              y="437"
              fill="#CDD0D4"
              rx="8"
            ></rect>
            <rect
              width="195"
              height="65"
              x="974"
              y="437"
              fill="#CDD0D4"
              rx="8"
            ></rect>
            <rect
              width="195"
              height="65"
              x="1207"
              y="437"
              fill="#CDD0D4"
              rx="8"
            ></rect>
          </g>
        </g>
        <g>
          <rect
            width="1408"
            height="108"
            x="22"
            y="291"
            fill="#EBEAEA"
            rx="8"
          ></rect>
          <g>
            <rect
              width="195"
              height="65"
              x="42"
              y="315"
              fill="#CDD0D4"
              rx="8"
            ></rect>
            <rect
              width="195"
              height="65"
              x="275"
              y="315"
              fill="#CDD0D4"
              rx="8"
            ></rect>
            <rect
              width="195"
              height="65"
              x="508"
              y="315"
              fill="#CDD0D4"
              rx="8"
            ></rect>
            <rect
              width="195"
              height="65"
              x="741"
              y="315"
              fill="#CDD0D4"
              rx="8"
            ></rect>
            <rect
              width="195"
              height="65"
              x="974"
              y="315"
              fill="#CDD0D4"
              rx="8"
            ></rect>
            <rect
            className="animate-pulse"
              width="195"
              height="65"
              x="1207"
              y="315"
              fill="#CDD0D4"
              rx="8"
            ></rect>
          </g>
        </g>
        <g>
          <rect
            width="1408"
            height="108"
            x="22"
            y="534"
            fill="#EBEAEA"
            rx="8"
          ></rect>
          <g>
            <rect
              width="195"
              height="65"
              x="42"
              y="558"
              fill="#CDD0D4"
              rx="8"
            ></rect>
            <rect
              width="195"
              height="65"
              x="275"
              y="558"
              fill="#CDD0D4"
              rx="8"
            ></rect>
            <rect
              width="195"
              height="65"
              x="508"
              y="558"
              fill="#CDD0D4"
              rx="8"
            ></rect>
            <rect
            className="animate-pulse"
              width="195"
              height="65"
              x="741"
              y="558"
              fill="#CDD0D4"
              rx="8"
            ></rect>
            <rect
              width="195"
              height="65"
              x="974"
              y="558"
              fill="#CDD0D4"
              rx="8"
            ></rect>
            <rect
              width="195"
              height="65"
              x="1207"
              y="558"
              fill="#CDD0D4"
              rx="8"
            ></rect>
          </g>
        </g>
        <g>
          <rect
            width="1408"
            height="108"
            x="22"
            y="657"
            fill="#EBEAEA"
            rx="8"
          ></rect>
          <g>
            <rect
              width="195"
              height="65"
              x="42"
              y="681"
              fill="#CDD0D4"
              rx="8"
            ></rect>
            <rect
              width="195"
              height="65"
              x="275"
              y="681"
              fill="#CDD0D4"
              rx="8"
            ></rect>
            <rect
              width="195"
              height="65"
              x="508"
              y="681"
              fill="#CDD0D4"
              rx="8"
            ></rect>
            <rect
              width="195"
              height="65"
              x="741"
              y="681"
              fill="#CDD0D4"
              rx="8"
            ></rect>
            <rect
              width="195"
              height="65"
              x="974"
              y="681"
              fill="#CDD0D4"
              rx="8"
            ></rect>
            <rect
              width="195"
              height="65"
              x="1207"
              y="681"
              fill="#CDD0D4"
              rx="8"
            ></rect>
          </g>
        </g>
      </g>
    </g>
    <defs>
      <clipPath id="clip0_0_1">
        <path
          fill="#fff"
          d="M0 0H1444V868H0z"
          transform="translate(-12 -114)"
        ></path>
      </clipPath>
    </defs>
  </svg>
  </>
}


